// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyPd7aLx9qoKnwLk3YPxSuujQVUoK6-wA',
    appId: '1:691806673031:web:1bfb5cc4f87e6a40b60022',
    messagingSenderId: '691806673031',
    projectId: 'medigarden-da20f',
    authDomain: 'medigarden-da20f.firebaseapp.com',
    storageBucket: 'medigarden-da20f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO1z7ysAW8apmxuEscdQLiPnPOqGjiLEQ',
    appId: '1:691806673031:android:5939d8c0a881a17db60022',
    messagingSenderId: '691806673031',
    projectId: 'medigarden-da20f',
    storageBucket: 'medigarden-da20f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxiDLWwR3Y0h8xOekIed2NLxP_nw8e9gU',
    appId: '1:691806673031:ios:1daa7f191342d9d5b60022',
    messagingSenderId: '691806673031',
    projectId: 'medigarden-da20f',
    storageBucket: 'medigarden-da20f.appspot.com',
    iosBundleId: 'com.example.medigard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxiDLWwR3Y0h8xOekIed2NLxP_nw8e9gU',
    appId: '1:691806673031:ios:fcfbcbd5e2715bdeb60022',
    messagingSenderId: '691806673031',
    projectId: 'medigarden-da20f',
    storageBucket: 'medigarden-da20f.appspot.com',
    iosBundleId: 'com.example.medigard.RunnerTests',
  );
}
